[project]
scalaVersion       = "2.11.12"
scalaJsVersion     = "0.6.29"
scalaNativeVersion = "0.3.9"
scalaOptions       = [
  "-encoding", "UTF-8",
  "-unchecked",
  "-deprecation",
  "-Xfuture",
  "-Yno-adapted-args",
  "-Ywarn-numeric-widen",
  "-feature"
]
testFrameworks = [
  "org.scalatest.tools.Framework",
  "org.scalacheck.ScalaCheckFramework"
]

[module.toml]
root    = "shared"
sources = ["shared/src/main/scala"]
targets = ["js", "jvm", "native"]
scalaDeps = [
  ["org.scalameta", "fastparse", "1.0.1"],
  ["com.chuusai", "shapeless", "2.3.3"]
]

[module.toml.jvm]
root    = "jvm"
sources = ["jvm/src/main/scala"]

[module.toml.test.jvm]
sources = ["shared/src/test/scala", "jvm/src/test/scala"]
scalaDeps = [
  ["org.scalatest" , "scalatest" , "3.0.8" ],
  ["org.scalacheck", "scalacheck", "1.14.2"]
]

[module.toml.js]
root    = "js"
sources = ["js/src/main/scala"]

[module.toml.test.js]
sources = ["shared/src/test/scala"]
scalaDeps = [
  ["org.scalatest" , "scalatest" , "3.0.8" ],
  ["org.scalacheck", "scalacheck", "1.14.2"]
]

[module.toml.native]
root         = "native"
scalaVersion = "2.11.12"
sources      = ["native/src/main/scala"]

[module.toml.test.native]
# Exclude GeneratedSpec.scala and Generators.scala
sources = [
  "shared/src/test/scala/toml/CodecSpec.scala",
  "shared/src/test/scala/toml/EmbedSpec.scala",
  "shared/src/test/scala/toml/GenerationSpec.scala",
  "shared/src/test/scala/toml/RulesSpec.scala",
  "shared/src/test/scala/toml/TestHelpers.scala",
]
scalaDeps = [
  ["org.scalatest", "scalatest", "3.2.0-SNAP10"]
]
